# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpudata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.FloatField(default=100)),
                ('distance', models.FloatField(default=1)),
                ('price', models.FloatField(default=5000)),
            ],
        ),
    ]
