# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_cpudata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpudata',
            old_name='distance',
            new_name='gen',
        ),
        migrations.AddField(
            model_name='cpudata',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpudata',
            name='years',
            field=models.IntegerField(default=2558),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='brand',
            field=models.CharField(max_length=200),
        ),
    ]
