# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161207_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='gen',
            field=models.CharField(max_length=50),
        ),
    ]
